### ISSUE TITLE
Funktioniert bei mir nicht (Ubuntu 18.10)

### ISSUE THREAD

**Issue by zImPatrick** [DaylySmile/TempCheck#1]
TempCheck funktioniert bei mir nicht. Hier ist, was kommt wenn ich es öffne:
![image](https://user-images.githubusercontent.com/23613354/54042462-77c35500-41ca-11e9-8e76-67ca19c8b405.png)

Die Datei sieht aber normal aus.
![image](https://user-images.githubusercontent.com/23613354/54042484-87db3480-41ca-11e9-830f-3a9fca2ed360.png)

**Comment by DaylySmile** [comment]
Upps, das ist ein Bug, der durch die unterschiedlichen Distributionen geschuldet ist.
Probiere mal, das #!/bin/bash durch #!/bin/sh zu ersetzen. 
Andernfalls werde ich mich wohl gezwungen sehen, eine Ubuntu-Variante des TempChecks zu machen.

**Comment by zImPatrick** [comment]
> Upps, das ist ein Bug, der durch die unterschiedlichen Distributionen geschuldet ist.
> Probiere mal, das #!/bin/bash durch #!/bin/sh zu ersetzen.
> Andernfalls werde ich mich wohl gezwungen sehen, eine Ubuntu-Variante des TempChecks zu machen.

Okay, danke für die Antwort! Ich hole dann mal wieder das Script, und ersetze #!/bin/bash mit #!/bin/sh

**Comment by zImPatrick** [comment]
![image](https://user-images.githubusercontent.com/23613354/54228823-48cb1d00-4503-11e9-8d83-47bc32cb470f.png)
Es geht doch immernoch nicht. Ich denke, das hat etwas mit diesem ^M zu tun.

**Comment by DaylySmile** [comment]
Ich habe dort kein ^M hinzugefügt.
Probiere mal, das Skript mit dem normalen Terminal auszuführen. Vielleicht hilft ja das.

**Comment by DaylySmile** [comment]
Okay, ähm, sorry für die Störung um diese Uhrzeit, aber es liegt daran, dass die Datei im DOS-Modus (also /n/r) gespeichert wurde. Da liegt wohl leider ein Problem vor, was ich mit dem nächsten Update fixen werde.

**Comment by zImPatrick** [comment]
Okay, danke!

Eigentlich geht es auch nicht wirklich auf Ubuntu, da ein Befehl den du
nutzt nicht existiert.

Dayly_Smile <notifications@github.com> schrieb am Di., 12. März 2019, 22:14:

**Comment by DaylySmile** [comment]
Okay, ich werde bald eine Version für Ubuntu 18.x releasen. 
Bitte nicht wundern, wenn es ein paar Kompatibilitätsprobleme geben könnte, ich teste es auf Ubuntu 18.04 LTS.
Falls es noch Probleme geben sollte, öffne ein weiteres Issue oder schreibe mir ne Mail an daylysmileyt@gmail.com.
